name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          # Use npm ci when a lockfile exists for reproducible installs, else fall back to npm install
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Build (TypeScript)
        run: npm run build

      - name: Run tests
        env:
          CI: true
        run: npm test
